- hosts: coeus
  roles:
  - ansible-prometheus

# Targets to populate the prometheus.yaml file on the prometheus server
# Each node needs to be specified in roles/ansible-prometheus/defaults/main.yml under prometheus_scrape_configs:
# run export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES if playbook fails with
# [__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.

  vars:
    prometheus_storage_retention: "7d"
    prometheus_storage_retention_size: "12GB"
    prometheus_targets:
    prometheus_alertmanager_config:
#      - scheme: https
      - scheme: http
#        path_prefix: "alertmanager/"
        static_configs:
#        - targets: ["alertmanager.infrastructure.k8s.contensis.cloud"]
        - targets: ["127.0.0.1:9093"]
    prometheus_global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
    prometheus_scrape_configs:
      - job_name: "prometheus"
        metrics_path: "{{ prometheus_metrics_path }}"
        static_configs:
          - targets:
              - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
      - job_name: "node"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/node.yml"
      - job_name: "coeus"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/coeus.yml"
    prometheus_targets:
      - node:
        - targets:
          - 134.209.25.208:9100
      - coeus:
        - targets:
          - 10.128.38.4:8080
    prometheus_alert_rules:

    # Minor Alerts #

    # Server Down for over 5 minutes
      - alert: InstanceDown
        expr: "up == 0"
        for: 5m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} down{% endraw %}"
    # Critical CPU above 95% for more than 5 minutes
      - alert: CriticalCPULoad
        expr: '100 - (avg by (instance) (irate(node_cpu_seconds_total{job="node",mode="idle"}[5m])) * 100) > 95'
        for: 2m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has Critical CPU load for more than 2 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} - Critical CPU load{% endraw %}"
    # Critical RAM usage above 98% for more than 5 minutes
      - alert: CriticalRAMUsage
        expr: '(1 - ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100 > 98'
        for: 5m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} has Critical Memory Usage more than 5 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} has Critical Memory Usage{% endraw %}"
    # Low Disk space
      - alert: LowDiskSpace
        expr: 'node_filesystem_free_bytes{mountpoint!~"^/run(/.*|$)",fstype!~"(squashfs|fuse.*)",job="node"} / node_filesystem_size_bytes{job="node"} < 0.3'
        for: 4m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has less than 30% space remaining.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} - Low disk space usage{% endraw %}"
     # Low Disk space ( Cassandra Data )
      - alert: LowDiskSpace
        expr: '(node_filesystem_avail_bytes{device="/dev/sdb",fstype="ext4",job="node",mountpoint="/data"})/(node_filesystem_size_bytes{device="/dev/sdb",fstype="ext4",job="node",mountpoint="/data"})*100 < 60'
        for: 4m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has less than 60% space remaining.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} - Low disk space usage{% endraw %}"
    # Critical Disk space ( Cassandra Data )
      - alert: CriticalDiskSpace
        expr: '(node_filesystem_avail_bytes{device="/dev/sdb",fstype="ext4",job="node",mountpoint="/data"})/(node_filesystem_size_bytes{device="/dev/sdb",fstype="ext4",job="node",mountpoint="/data"})*100 < 50'
        for: 4m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has less than 50% space remaining.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} - Critical disk space usage{% endraw %}"
    # Server requires a reboot
      - alert: RebootRequired
        expr: "node_reboot_required > 0"
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} requires a reboot.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} - reboot required{% endraw %}"
    # Cassandra Service is not running
      - alert: Cassandra Service Down
        expr: 'node_systemd_unit_state{name="cassandra.service",state="active"} == 0'
        for: 1m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} down{% endraw %}"
    # The Cassandra Reaper service is not running - It is required to perform repairs
      - alert: Cassandra Reaper Service Down
        expr: 'absent(node_systemd_unit_state{name="cassandra-reaper.service"}) == 1'
        for: 5m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} down{% endraw %}"
    # Node Exporter has stopped for more than 5 minutes ( probably wont work )
      - alert: Node Exporter Service Down
        expr: 'node_systemd_unit_state{name="node_exporter.service",state="active"} == 0'
        for: 5m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} down{% endraw %}"
    # Cassandra Node exporter has stopped, no Cassandra stats being collected
      - alert: Cassandra Node Exporter Service Down
        expr: 'node_systemd_unit_state{name="prometheus-cassandra-exporter.service",state="active"} == 0'
        for: 5m
        labels:
          severity: minor
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} down{% endraw %}"

    # Significant Alerts #

    # Critical Disk space
      - alert: CriticalDiskSpace
        expr: 'node_filesystem_free_bytes{mountpoint!~"^/run(/.*|$)",fstype!~"(squashfs|fuse.*)",job="node"} / node_filesystem_size_bytes{job="node"} < 0.1'
        for: 4m
        labels:
          severity: significant
        annotations:
          description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has less than 50% space remaining.{% endraw %}"
          summary: "{% raw %}Instance {{ $labels.instance }} - Critical disk space usage{% endraw %}"

    # Major Alerts #

    # Critical Alerts #
