exporter_port: 8000 # Port on which prometheus can call this exporter to get metrics
log_level: info
json_data_url: http://10.128.72.4/face.json # Url to get json data used for fetching metric values
metric_name_prefix: ceous # All metric names will be prefixed with this value
metrics:
- name: total_nodes # Final metric name will be kong_cluster_total_nodes
  description: Total number of nodes in kong cluster
  path: $.total
- name: face_count # Number of faces
  description: Number of faces
  path: count($.faceId)
- name: female_count # Number of females
  description: Number of faces
  path: count($.gender is "female")
- name: male_count # Number of males
  description: Number of faces
  path: count($.gender is "male")

